name: prf-simple
version: 0

language: GHC2021

library:
  source-dirs: src
  dependencies:
    - base

tests:
  prf-simple-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - hedgehog
      - prf-simple
      - sydtest
      - sydtest-hedgehog
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

