name: prf-typed
version: 0

language: GHC2021

library:
  source-dirs: src
  dependencies:
    - base
    - fixed-vector
    - template-haskell

tests:
  prf-typed-test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - base
      - hedgehog
      - prf-typed
      - sydtest
      - sydtest-hedgehog
    ghc-options: -threaded -rtsopts -with-rtsopts=-N

